name       : gnome-control-center
version    : 3.38.2
release    : 99
source     :
    - git|https://gitlab.gnome.org/GNOME/gnome-control-center.git : 3.38.2
license    : GPL-2.0-only
component  : desktop.gnome
summary    : The GNOME Control Center
description: |
    The GNOME Control Center
optimize   : speed
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(colord-gtk)
    - pkgconfig(com_err)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gnome-bluetooth-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(goa-backend-1.0)
    - pkgconfig(grilo-0.3)
    - pkgconfig(gsound)
    - pkgconfig(ibus-1.0)
    - pkgconfig(krb5)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libnma)
    - pkgconfig(libpulse)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwacom)
    - pkgconfig(ModemManager)
    - pkgconfig(pwquality)
    - pkgconfig(smbclient)
    - pkgconfig(udisks2)
    - pkgconfig(upower-glib)
    - bluez
    - cups-devel
    - docbook-xml
    - gnome-common
patterns   :
    - devel :
        - /usr/share/pkgconfig/gnome-keybindings.pc
rundeps    :
    - bolt # Thunderbolt support
    - cups-pk-helper
    - glib-networking
    - gnome-color-manager
    - gvfs-goa
    - libgnomekbd
    - sound-theme-freedesktop
setup      : |
    %apply_patches
    # They pushed gvc to a commit that requires pulseaudio 13+
    pushd subprojects/gvc
    git checkout ec5cf3e0de6715803e64b65abb059e2155b3d6de
    popd
    pushd subprojects/libhandy
    %patch -p1 < $pkgfiles/libhandy-reverts/0001-Don-t-install-cruft.-Change-so-name-to-reflect-behav.patch
    popd
    %meson_configure -Dcheese=false -Ddocumentation=true
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm $installdir/%libdir%/*.so

    # support keyfile backend in gnome-control-center
    install -m 00644 $pkgfiles/gnome-control-center.keyrules $installdir/usr/share/polkit-1/rules.d/.
