name       : gnome-control-center
version    : 3.20.1
release    : 44
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-control-center/3.20/gnome-control-center-3.20.1.tar.xz : ce6474fc60f78ed3cfaf555e55a52ec3ebb6437fa184e08ad6077bbec380a1ed
license    : GPL-2.0
component  : desktop.gnome
summary    : The GNOME Control Center
builddeps  :
    - bluez
    - pkgconfig(accountsservice)
    - pkgconfig(clutter-1.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(colord-gtk)
    - pkgconfig(com_err)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(ibus-1.0)
    - pkgconfig(gl)
    - pkgconfig(gnome-bluetooth-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(goa-backend-1.0)
    - pkgconfig(grilo-0.3)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libnm-gtk)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwacom)
    - pkgconfig(NetworkManager)
    - pkgconfig(ModemManager)
    - pkgconfig(pwquality)
    - pkgconfig(smbclient)
    - pkgconfig(upower-glib)
    - cups-devel
    - docbook-xml
    - kerberos-devel
patterns   :
    - devel :
        - /usr/share/pkgconfig/gnome-keybindings.pc
rundeps    :
    - cups-pk-helper
    - glib-networking
    - gnome-color-manager
    - gvfs-goa
    - libgnomekbd
    - sound-theme-freedesktop
    - vino
description: |
    The GNOME Control Center
setup      : |
    %patch -p1 < $pkgfiles/0001-panels-Do-not-hide-items-from-menu-listings-i.e.-Bud.patch
    %patch -p1 < $pkgfiles/0001-user-accounts-Disable-GDM-specific-functionality-we-.patch
    %patch -p1 < $pkgfiles/0001-Add-Solus-Branding.patch
    %configure --disable-static --enable-systemd --enable-documentation
build      : |
    %make
install    : |
    %make_install
