name       : gnome-control-center
version    : 3.22.1
release    : 46
source     :
    - https://download.gnome.org/sources/gnome-control-center/3.22/gnome-control-center-3.22.1.tar.xz : 5d69295bc43176392d65b3bdbe60eb85cdcac95b1ef76b86933f3ba9cf48091a
license    : GPL-2.0
component  : desktop.gnome
summary    : The GNOME Control Center
builddeps  :
    - bluez
    - pkgconfig(accountsservice)
    - pkgconfig(clutter-1.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(colord-gtk)
    - pkgconfig(com_err)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(ibus-1.0)
    - pkgconfig(gl)
    - pkgconfig(gnome-bluetooth-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(goa-backend-1.0)
    - pkgconfig(grilo-0.3)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libnm-gtk)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwacom)
    - pkgconfig(NetworkManager)
    - pkgconfig(ModemManager)
    - pkgconfig(pwquality)
    - pkgconfig(smbclient)
    - pkgconfig(upower-glib)
    - cups-devel
    - docbook-xml
    - gnome-common
    - kerberos-devel
patterns   :
    - devel :
        - /usr/share/pkgconfig/gnome-keybindings.pc
rundeps    :
    - cups-pk-helper
    - glib-networking
    - gnome-color-manager
    - gvfs-goa
    - libgnomekbd
    - sound-theme-freedesktop
    - vino
description: |
    The GNOME Control Center
setup      : |
    %apply_patches
    %reconfigure --disable-static --enable-systemd --enable-documentation
build      : |
    %make
install    : |
    %make_install
