name       : gnome-control-center
version    : 3.34.0.1
release    : 82
source     :
    - https://download.gnome.org/sources/gnome-control-center/3.34/gnome-control-center-3.34.0.1.tar.xz : 0a5ba598da8574e20599631cb00d8a8d2ae06be05dbb819611f337e6ef5a23cb
license    : GPL-2.0-only
component  : desktop.gnome
summary    : The GNOME Control Center
description: |
    The GNOME Control Center
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(clutter-1.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(colord-gtk)
    - pkgconfig(com_err)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(ibus-1.0)
    - pkgconfig(gl)
    - pkgconfig(gnome-bluetooth-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(goa-backend-1.0)
    - pkgconfig(grilo-0.3)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gsound)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libnma)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libwacom)
    - pkgconfig(ModemManager)
    - pkgconfig(pwquality)
    - pkgconfig(smbclient)
    - pkgconfig(udisks2)
    - pkgconfig(upower-glib)
    - bluez
    - cups-devel
    - docbook-xml
    - gnome-common
    - kerberos-devel
patterns   :
    - devel :
        - /usr/share/pkgconfig/gnome-keybindings.pc
rundeps    :
    - bolt # Thunderbolt support
    - cups-pk-helper
    - glib-networking
    - gnome-color-manager
    - gvfs-goa
    - libgnomekbd
    - sound-theme-freedesktop
    - vino
setup      : |
    %apply_patches
    %meson_configure -Dcheese=false -Ddocumentation=true
build      : |
    %ninja_build
install    : |
    %ninja_install

    # support keyfile backend in gnome-control-center
    install -m 00644 $pkgfiles/gnome-control-center.keyrules $installdir/usr/share/polkit-1/rules.d/.
