name        : gnome-control-center
version     : 3.16.1
release     : 12
source      :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-control-center/3.16/gnome-control-center-3.16.1.tar.xz : eec9f59d6f17193c6a05030f9ce585118e64c6ab8d997ce962803129b1ad7b1f
license     : GPL-2.0+
summary     : The GNOME Control Center
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(upower-glib)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(gl)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(goa-backend-1.0)
    - pkgconfig(grilo-0.2)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(colord-gtk)
    - pkgconfig(accountsservice)
    - pkgconfig(ibus-1.0)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(pwquality)
    - pkgconfig(NetworkManager)
    - pkgconfig(ModemManager)
    - pkgconfig(libnm-gtk)
    - pkgconfig(libwacom)
    - pkgconfig(clutter-1.0)
    - pkgconfig(clutter-gtk-1.0)
    - kerberos-devel
description : |
    The GNOME Control Center
setup      : |
    %patch -p1 < $pkgfiles/0001-panels-Do-not-hide-items-from-menu-listings-i.e.-Bud.patch
    %patch -p1 < $pkgfiles/0001-user-accounts-Disable-GDM-specific-functionality-we-.patch
    %configure --disable-static --enable-systemd --disable-documentation
build      : |
    %make
install    : |
    %make_install
